#!/usr/bin/perl

# ============================================================================
# Copyright (C) 2002 Michael J. Wohlgemuth. All rights reserved; 
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
# OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
# ============================================================================

use strict;
use linksysmon;

my $linksysmon = new linksysmon();

my $prog = "linksysmon-ipchange";
my $host;
my $ip;
my $date;
my $time;

if (@ARGV == 4) {
    ($host, $ip, $date, $time) = @ARGV;
} 
else {
    die "Usage: $prog <hostname> <ip address> <date> <time>\n";
}

my $mailto = $linksysmon->MailTo();

my $mail = $linksysmon->MailPath()." -s \"linksys at $host got new address $ip on $date $time\" ".join(' ', @$mailto);

open (MAIL, "| $mail") || die "Error: Unable to send mail\n";
print MAIL "This is an automated message from $prog\n";
close (MAIL);

print "Notified ".join(", ", @$mailto)." of $host IP address change to $ip\n";

